[workspace]
members = [
    "src/onchain360_backend",
    "src/soclynk_backend",
]
resolver = "2"

[workspace.dependencies]
candid = "0.8.4"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.0"
ic-stable-structures = "0.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"